name: metalwailers
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.0
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false # En Windows, esto debe estar en false
  remove_alpha_ios: true
  image_path: "assets/logo/logoweb.png"
  adaptive_icon_foreground: "assets/icon/logoweb.png"

  web:
    generate: true
    image_path: "assets/logo/logoweb.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
